import type { StrategyNumber } from "./types";

export const strategies = [
  {
    n: 1,
    id: "direct",
    name: "Direct",
    meaning: "Say something straight away",
    when: "Use Direct when the situation is low-stakes, the person affected wants to speak up, and you can intervene without escalating the scene.",
    whenNot: "Avoid Direct if the person affected is already being targeted, if the situation feels volatile, or if you would be putting yourself or someone else at risk.",
    definition: "Address the behavior clearly and immediately when it is safe to do so.",
    about: [
      "Direct means you speak to the person causing harm. You name what is happening and ask them to stop. Keep it short and calm. You are not trying to win an argument or teach a lesson, only to stop the behavior.",
      "Direct works best when you know the people, the setting is calm, and the person affected wants support. A short sentence from a peer can change the mood of a whole room, because it shows that others see the behavior too.",
      "After you speak, turn your attention to the person affected. Ask if they are okay. Do not debate. If the person causing harm pushes back, you can repeat yourself once, then walk away or switch to another D.",
    ],
    tips: ["Use one short sentence. Do not explain or argue.", "Speak to the behavior, not the person’s character.", "Afterwards, check in with the person affected."],
    scenes: [
      { where: "At a party", text: "“Hey, she said no. Leave it.”" },
      { where: "In a group chat", text: "“Not cool. Delete that, please.”" },
      { where: "In class", text: "“Let them finish. They were talking.”" },
      { where: "With friends", text: "“That joke isn’t funny. Drop it.”" },
    ],
    photo: { id: 10578908, by: "cottonbro studio" },
    examples: ["“Please stop.”", "“They asked you to stop.”", "“That comment isn’t okay.”"],
    situation: "Someone repeatedly comments on another student’s body after being asked to stop.",
    question: "Which response is Direct?",
    options: ["“Hey, come help me grab something from the kitchen.”", "“They asked you to stop. Leave them alone.”", "Find the host and ask them to step in."],
    answer: 1,
    why: "It names the behavior and asks for it to stop.",
    practice: "Write one clear sentence you could say directly.",
    placeholder: "That isn’t okay. Please stop.",
    fit: [
      { text: "A friend makes a crude joke about someone in your group. Everyone is calm, and you know him well.", ok: true },
      { text: "A stranger on the platform is shouting at someone and looks ready to fight.", ok: false },
      { text: "A classmate keeps talking over a quieter student. The room is calm, and the student looks to you for support.", ok: true },
    ],
    spot: [
      { text: "“Hey, that’s not funny. Knock it off.”", ok: true },
      { text: "Spill your drink nearby so the conversation breaks up.", ok: false },
      { text: "“Stop. She already said no.”", ok: true },
      { text: "Ask the bartender to keep an eye on them.", ok: false },
    ],
  },
  {
    n: 2,
    id: "distract",
    name: "Distract",
    meaning: "Create a diversion",
    when: "Use Distract when you need to interrupt the interaction without escalating it. A diversion can give the person affected space to leave or change the subject.",
    whenNot: "Avoid Distract if the situation is already physical, if the person affected is being followed, or if a diversion would make the scene more confusing.",
    definition: "Create a diversion that interrupts the situation without directly confronting the person causing harm.",
    about: [
      "Distract means you interrupt the moment without naming the harm. You start a conversation, ask a question, or create a small scene that breaks the focus. The person causing harm loses their moment, and the person affected gets a chance to leave.",
      "It is often the safest D, because nobody is confronted. It works well when speaking up directly could make things worse, or when you are not sure what is happening but something feels wrong.",
      "Good distractions are ordinary: asking for directions, pretending to know the person, spilling a drink, or asking for help. Speak to the person affected, not to the person causing harm.",
    ],
    tips: ["Talk to the person affected, not the person causing harm.", "Keep it ordinary: a question, a request, a fake errand.", "Stay with them until the moment has passed."],
    scenes: [
      { where: "At a party", text: "“There you are! Your roommate is looking for you.”" },
      { where: "On the bus", text: "“Excuse me, do you know which stop is for campus?”" },
      { where: "At a bar", text: "Accidentally bump the table so everyone looks up." },
      { where: "In a hallway", text: "“Hey, can you help me carry this?”" },
    ],
    photo: { id: 7269735, by: "MART PRODUCTION" },
    examples: ["“Hey, I’ve been looking for you.”", "“Can you help me with something?”"],
    situation: "Your friend is being pressured to leave a party with someone they just met.",
    question: "Which response uses Distract?",
    options: ["“Leave her alone.”", "Tell the host what is happening.", "“Maya, your roommate is looking everywhere for you. Come with me.”"],
    answer: 2,
    why: "It gives Maya a natural reason to leave without direct confrontation.",
    practice: "Write your own distraction or exit line.",
    placeholder: "Hey, our ride is here. Come on.",
    fit: [
      { text: "Someone at a party keeps cornering your friend, who keeps looking over at you.", ok: true },
      { text: "A man is pushing someone against a wall.", ok: false },
      { text: "On a calm bus, a man keeps asking a student for her number after she says no.", ok: true },
    ],
    spot: [
      { text: "“Sorry, is this the line for the bathroom?”", ok: true },
      { text: "Write down the time and the bus number.", ok: false },
      { text: "“Your phone is ringing. Come check it with me.”", ok: true },
      { text: "Message her later to ask if she is okay.", ok: false },
    ],
  },
  {
    n: 3,
    id: "delegate",
    name: "Delegate",
    meaning: "Get someone else",
    when: "Use Delegate when the situation needs authority, staff, or security. Get someone who can act faster, more safely, or with more credibility.",
    whenNot: "Avoid Delegate if the person affected does not want staff involved, if the situation is already being handled well, or if you can act more quickly yourself.",
    definition: "Get another person who may be better positioned to help.",
    about: [
      "Delegate means you get help from someone better placed to act. That might be a person with authority, like a manager, RA, conductor, or security guard. It might also be a friend of the person affected.",
      "Delegate is useful when you do not feel safe acting alone, when the situation needs authority, or when someone else knows the people involved. You still take action: you notice, you find the right person, and you tell them clearly what is happening.",
      "Be specific when you ask for help. Say where, who, and what you saw. If you cannot leave, ask someone near you to go and get help while you stay close.",
    ],
    tips: ["Pick a person with authority or a close friend.", "Be specific: where, who, and what you saw.", "If you stay behind, keep the person affected in sight."],
    scenes: [
      { where: "At a bar", text: "Tell the bartender: “The man in the grey jacket keeps grabbing her.”" },
      { where: "On a train", text: "Find the conductor and describe what is happening in which car." },
      { where: "In a dorm", text: "Call the RA on duty and ask them to come to the common room." },
      { where: "At a party", text: "Find her friends and say: “She looks uncomfortable. Can you go to her?”" },
    ],
    photo: { id: 19038283, by: "Melih Turkmenoglu" },
    examples: ["A friend", "An RA", "A bartender", "A professor", "Event staff", "Security"],
    situation: "A student on a train keeps following another passenger after she changes seats. You do not feel safe confronting him directly.",
    question: "What could you do?",
    options: ["Ignore it because direct confrontation feels unsafe.", "Tell the conductor or transit staff what is happening.", "Start arguing with him."],
    answer: 1,
    why: "It brings in someone who can help while you stay safe.",
    practice: "Who could you delegate to in this situation?",
    placeholder: "The conductor, or another passenger near her",
    fit: [
      { text: "A guest keeps grabbing people at a bar, and a bouncer is standing nearby.", ok: true },
      { text: "Your friend asks you not to tell anyone, especially the RA.", ok: false },
      { text: "On a late train, a man keeps moving closer to a passenger, and you feel unsafe stepping in alone.", ok: true },
    ],
    spot: [
      { text: "Find her friends and tell them she needs them.", ok: true },
      { text: "“Stop. She said no.”", ok: false },
      { text: "Tell event staff what you saw and where.", ok: true },
      { text: "“Hey, can you help me find my phone?”", ok: false },
    ],
  },
  {
    n: 4,
    id: "delay",
    name: "Delay",
    meaning: "Check in after",
    when: "Use Delay when the moment to act has passed but the person affected still needs support. Check in afterwards and offer next steps.",
    whenNot: "Avoid Delay if the person affected needs help right now, if the situation is still escalating, or if you are the only person who can act.",
    definition: "Check in with someone after the immediate moment has passed.",
    about: [
      "Delay means you check in with the person affected after the moment has passed. Sometimes you cannot act in time, or acting would not be safe. You can still help afterwards.",
      "Harm can feel lonely. A simple message that says “I saw that, it was not okay” tells the person they are not alone and that they are not imagining it. That support can matter as much as stopping the moment itself.",
      "Let the person lead. Ask what they need, offer specific help, and accept their answer. Do not push them to report, and do not share what happened with others without their consent.",
    ],
    tips: ["Name what you saw and that it was not okay.", "Ask what they need. Do not decide for them.", "Keep what they tell you private."],
    scenes: [
      { where: "After class", text: "“That comment was out of line. Are you okay?”" },
      { where: "By message", text: "“I saw what happened in the chat. I’m here if you want to talk.”" },
      { where: "After a party", text: "“Do you want me to walk you home?”" },
      { where: "Next day", text: "“Would it help if I came with you to talk to someone?”" },
    ],
    photo: { id: 5940844, by: "Kampus Production" },
    examples: ["“Are you okay?”", "“Do you want me to stay with you?”", "“Would you like help finding your friends?”"],
    situation: "You see a classmate being mocked during a group project. The conversation ends before you feel comfortable stepping in.",
    question: "What would Delay look like?",
    options: ["Message them afterward: “Hey, that wasn’t okay. Are you doing alright?”", "Pretend you did not notice.", "Post about the situation publicly."],
    answer: 0,
    why: "It checks in afterward and lets the person choose what support they want.",
    practice: "Write one thing you could say when checking in.",
    placeholder: "Hey, that wasn’t okay. Are you alright?",
    fit: [
      { text: "A teammate was mocked in a meeting that has now ended.", ok: true },
      { text: "Someone is being pulled out of a party right now and looks scared.", ok: false },
      { text: "A classmate was insulted in the hallway, and the person who did it has already left.", ok: true },
    ],
    spot: [
      { text: "“I saw what happened earlier. Do you want company?”", ok: true },
      { text: "Ask a teacher to step in right now.", ok: false },
      { text: "Text her the next morning to ask how she is doing.", ok: true },
      { text: "“Don’t talk to him like that.”", ok: false },
    ],
  },
  {
    n: 5,
    id: "document",
    name: "Document",
    meaning: "Note or record what happened",
    when: "Use Document when the person affected wants a record, when reporting may be helpful later, or when you need to pass information to someone else.",
    whenNot: "Avoid Document if the person affected does not want a record kept, if documenting would put them at greater risk, or if it delays taking action.",
    definition: "Preserve useful information about what happened while keeping consent and privacy in mind.",
    about: [
      "Document means you keep a record of what happened. That can be written notes, saved messages, or details like the time, place, and who was there. A record can help the person affected later if they choose to report.",
      "Document is about the person affected, not about you. Before you record, check that someone is already helping, or that the person is safe. Never share a record or post it online without their consent.",
      "For online harm, save the details rather than the harmful content itself. Note who posted, where, and when. If the content is a private image, do not save or forward it. Report it to the platform instead.",
    ],
    tips: ["Make sure someone is helping first.", "Record facts: time, place, who, what.", "Give the record to the person affected. Never post it."],
    scenes: [
      { where: "In a group chat", text: "Note the chat name, who posted, and the time. Do not save the image." },
      { where: "On the street", text: "Write down the time, the corner, and what the person looked like." },
      { where: "At work", text: "Keep a dated note of each comment you hear." },
      { where: "Afterwards", text: "“I wrote down what I saw. Do you want it?”" },
    ],
    photo: { id: 11391948, by: "Towfiqu barbhuiya" },
    examples: ["Note the time, the place, and who was there.", "Save who posted and when, not the image itself.", "Give the record to the person affected."],
    situation: "Someone posts a private image of another student in a group chat without their consent.",
    question: "Which response best shows Document?",
    options: ["Forward the image to a friend as proof.", "Preserve only the information needed to report what happened without spreading the image further.", "Repost it publicly to call the person out."],
    answer: 1,
    why: "Documentation should reduce harm, not spread the image further.",
    practice: "What information is actually necessary to preserve?",
    placeholder: "The group name, who posted it, and the time",
    fit: [
      { text: "The person affected asks you to note what you saw so she can report it later.", ok: true },
      { text: "The harassment is still going on, and nobody else is helping.", ok: false },
      { text: "A friend wants to report a pattern of threatening messages and asks for help keeping track.", ok: true },
    ],
    spot: [
      { text: "Note the date, the place, and who was there, then give the note to the person affected.", ok: true },
      { text: "“Come on, the movie’s about to start.”", ok: false },
      { text: "Save the account name and time of each message for her report.", ok: true },
      { text: "Forward the photo to a friend so there is proof.", ok: false },
    ],
  },
] as const;

export const guideSteps = ["Learn", "See it", "Recognize", "Practice"];

export type StrategyInfo = (typeof strategies)[number];

export const strategy = (n: StrategyNumber) => strategies[n - 1];
